from langchain_ollama import ChatOllama
from langchain_core.tools import tool
from langchain.agents import create_agent
from devops_tools import read_log_file, count_log_levels, show_docker_containers

#LLM 
llm=ChatOllama(
    model="llama3.2",
    base_url="http://localhost:11434",
    temperature=0 #randomness
)


#Tools
@tool
def analyze_logs(path):
    """
    This tool counts the log levels, INFO, WARNING, ERROR
    from a given file path
    """
    return count_log_levels(read_log_file(path))


@tool
def get_docker_containers():
    """
    This tool internally runs docker command via subprocess and gets
    the running and exited contaners information
    """
    return show_docker_containers()


# LLM + Tools = AI Agent
TOOLS=[analyze_logs, get_docker_containers]
SYSTEM_PROMPT="""
   **Task Description:**

As a DevOps Assistant, analyze a log file      
using the `analyze_logs` tool and Analyze the docker containers running locally using `get_docker_container` tool to provide       
a clear and concise summary of the log's       
contents. The input will be a file path,       
and the output should be a 
well-structured, easy-to-understand 
report.

**Specific Requirements:**

1. Take a log file path as input and
perform log analysis using the 
`analyze_logs` tool.
2. Output a clear and concise summary of       
the log's contents, including any notable      
issues, errors, or insights.
3. Ensure the output is well-structured        
and easy to read, with clear headings,
concise descriptions, and relevant 
details.
4. Provide the analysis in a format that       
is easily understandable by a DevOps
engineer or technical user.
5. Use relevant technical terms and
concepts to describe the log analysis,         
but avoid technical jargon that may be
unfamiliar to non-technical users.

**Example Output:**

The output should be a well-formatted
report that includes:

* A summary of the log file's contents
* A breakdown of the most notable issues       
or errors found in the log
* Relevant details about the log file's        
context, such as the application or 
system it was generated by
* Any recommendations or insights gained       
from the analysis

**Evaluation Criteria:**

The quality of the output will be
evaluated based on the following 
criteria:

* Accuracy and completeness of the log
analysis
* Clarity and concision of the output
* Relevance and usefulness of the 
analysis for a DevOps engineer or
technical user
* Adherence to the specific requirements       
outlined in the task description

**Note:**

Please ensure that the output is in a
format that can be easily understood by a      
human reader. Avoid using technical terms      
or concepts that may be unfamiliar to 
non-technical users. The output should be      
concise, clear, and well-structured, with      
a focus on providing actionable insights       
and recommendations for improving the log      
file's contents.

>>> make it short and crisp 
Here's a revised version of the prompt:

**Log Analysis Task:**

Analyze a log file using `analyze_logs`        
tool and provide a clear, concise report.

**Requirements:**

* Output a well-structured summary of the      
log's contents
* Identify notable issues or errors
* Provide actionable insights and 
recommendations
* Use relevant technical terms and
concepts
* Output format: easy to understand for        
DevOps engineers and technical users

**Evaluation Criteria:**

* Accuracy and completeness of log
analysis
* Clarity and concision of output
* Relevance and usefulness of analysis

"""
agent = create_agent(llm,tools=TOOLS,system_prompt=SYSTEM_PROMPT)

question=input("Enter your question for DevOps Agent:")
result=agent.invoke(
    {"messages":[("user",question)]}
)

print("\nThinking...\n")

print(result["messages"][-1].content)
